Mail database
lisperata/express-route pull request #2
Opened 2021-06-24 08:03 UTC by lisperata

![image](https://user-images.githubusercontent.com/56757215/123225850-cb612600-d4db-11eb-966e-117f92fb49e9.png)
![image](https://user-images.githubusercontent.com/56757215/123225866-cef4ad00-d4db-11eb-9a74-9c97f96caed8.png)
![image](https://user-images.githubusercontent.com/56757215/123225889-d2883400-d4db-11eb-8ecd-1f5d589b6a7c.png)
![image](https://user-images.githubusercontent.com/56757215/123225905-d74ce800-d4db-11eb-8f33-8d180ce2410d.png)

2021-06-24 08:54 UTC, CatDidenko requested changes
General incorrect things:
1) We should use module project structure. It mean all files related to one entity, should be in the same folder. 
Example: 
folder contact  should includes contacts controller, contacts service, contacts route and contacts model.
2) models/Contact.ts - It's not a model. It's a service, not a model file. Model describes an entity, not actions on it.
3) model/List.ts - it's not a model...
4) Don't get attached to the name of ORM that you use. Rename to more general - database. Also database folder should includes only configs for database. Models must be located in the appropriate modules. (contact model in contact folder)

2021-06-24 08:54 UTC, CatDidenko commented on sequelize/contactModel.ts
> +    type: "VARCHAR(36)",
Should be uuidv4 type and autogenerated

2021-06-24 08:54 UTC, CatDidenko commented on sequelize/listModel.ts
> +    type: "VARCHAR(36)",
Should be uuidv4 type and autogenerated

2021-06-24 08:54 UTC, CatDidenko commented on sequelize/listModel.ts
> +import pkg from "sequelize";
Bad naming

2021-06-25 08:57 UTC, lisperata commented on sequelize/contactModel.ts
> +    type: "VARCHAR(36)",
Used autogeneration

2021-06-25 08:57 UTC, lisperata commented on sequelize/listModel.ts
> +    type: "VARCHAR(36)",
Used autogeneration

2021-06-25 08:57 UTC, lisperata commented on sequelize/listModel.ts
> +import pkg from "sequelize";
Renamed

2021-06-25 21:06 UTC, CatDidenko approved these changes

2021-06-25 21:06 UTC, CatDidenko commented on contact/сontactService.ts
> +      ? this._convertParameterToQuery("email", email)
Please, use single quotes

2021-06-28 14:00 UTC, merged